kit_points: 20
food_points: 10
max_life: 100
cup_points: 50
num_bullets_picked_up: 5
max_bullets: 100
knife_base_damage: 1
knife_max_range: 60
gun_base_damage: 5
machine_gun_base_damage: 15
machine_gun_cooldown: 45
chain_cannon_base_damage: 10
chain_cannon_cooldown: 30
max_resurrections: 2

