#ifndef CONST_OBJECT_COMMAND_H_
#define CONST_OBJECT_COMMAND_H_

#define COMMAND_MOVE_RANGE_START 1
#define COMMAND_MOVE_RANGE_END 4

#define COMMAND_UP 1
#define COMMAND_DOWN 2
#define COMMAND_LEFT 3
#define COMMAND_RIGHT 4

#define COMMAND_ATACK 5

#define COMMAND_CHANGE_WEAPON_TO_KNIFE 6
#define COMMAND_CHANGE_WEAPON_TO_GUN 7
#define COMMAND_CHANGE_WEAPON_TO_MACHINE_GUN 8
#define COMMAND_CHANGE_WEAPON_TO_CHAIN_CANNON 9

#define COMMAND_OPEN_DOOR 10

#define COMMAND_TYPE_MOVE 11
#define COMMAND_TYPE_ATACK 12
#define COMMAND_TYPE_CHANGE_WEAPON 13
#define COMMAND_TYPE_OPEN_DOOR 14

#define SUCCESS_MSG "Success."
#define NO_KNIFE_IN_INVENTORY_ERROR_MSG "ERROR: No knife in inventory"
#define NO_GUN_IN_INVENTORY_ERROR_MSG "ERROR: No gun in inventory"
#define NO_MACHINE_GUN_IN_INVENTORY_ERROR_MSG "ERROR: No machine gun in inventory"
#define NO_CHAIN_CANNON_IN_INVENTORY_ERROR_MSG "ERROR: No chain cannon in inventory"

#endif    // CONST_OBJECT_COMMAND_H_
