#ifndef PROTOCOL_H
#define PROTOCOL_H

enum Opcode {
    EVENT_OPCODE = 0,
    ITEM_CHANGED_OPCODE,
    MESSAGE_OPCODE,
    COMMAND_OPCODE = 128
};

enum CommandOpcode {
    START_MOVING_UP_CMD = 0,
    START_MOVING_DOWN_CMD,
    START_MOVING_LEFT_CMD,
    START_MOVING_RIGHT_CMD,
    STOP_MOVING_CMD,
    START_ROTATING_LEFT,
    START_ROTATING_RIGHT,
    STOP_ROTATING,

    USE_WEAPON_CMD,
    RECIEVE_ATTACK_CMD,
    OPEN_DOOR_CMD,
    CHANGE_WEAPON_TO_KNIFE_CMD,
    CHANGE_WEAPON_TO_GUN_CMD,
    CHANGE_WEAPON_TO_MACHINE_GUN_CMD,
    CHANGE_WEAPON_TO_CHAIN_CANNON_CMD,
};

enum EventOpcode {
    MOVEMENT_EV = 0,
    ATTACK_EV,
    BE_ATTACKED_EV,
    DEATH_EV,
    RESURRECT_EV,
    CHANGE_LEVEL_EV
};

enum ItemOpcode {
    CLOSE_DOOR_ITM = 0
};

enum MessageOpcode {
    SUCCESS_MSSG = 0,
    ERROR_MSSG
};

#endif