#ifndef CONST_OBJECT_COMMAND_H_
#define CONST_OBJECT_COMMAND_H_

#define COMMAND_MOVE_RANGE_START 1
#define COMMAND_MOVE_RANGE_END 5

#define COMMAND_UP 1
#define COMMAND_DOWN 2
#define COMMAND_LEFT 3
#define COMMAND_RIGHT 4

#define COMMAND_ATACK 5

#define COMMAND_TYPE_MOVE 6
#define COMMAND_TYPE_ATACK 7

#endif    // CONST_OBJECT_COMMAND_H_
